### ISSUE TITLE
TPM vs raw counts

### ISSUE THREAD

**Issue by MartinFXP** [cbg-ethz/dce#21]
TPM seem to work as well or even better than raw counts with library size correction within the regression. Log normalization reduces accuracy.

[benchmark_f1-score.pdf](https://github.com/kpj/CausalPathways/files/5137333/benchmark_f1-score.pdf)
[benchmark_roc-auc.pdf](https://github.com/kpj/CausalPathways/files/5137334/benchmark_roc-auc.pdf)

**Comment by kpj** [comment]
Done by raw intelligence.
